# Docker compose command
# sudo docker compose up -d

# Using mongodev user/password credentials for development only
version: '3.7'

services:

# MongoDB server
  mongodb_fjm:
    image: mongo:4.4.19
    container_name: mongodb_fjm
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodev
      MONGO_INITDB_ROOT_PASSWORD: mongodev
    volumes:
      - ./mongo-volume:/data/db

# MongoDB management server
  mongomgt_fjm:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongomgt_fjm
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb_fjm
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongodev
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodev
      ME_CONFIG_BASICAUTH_USERNAME: mongodev
      ME_CONFIG_BASICAUTH_PASSWORD: mongodev
    depends_on:
      - mongodb_fjm